### ISSUE TITLE
Line in Input, how?

### ISSUE THREAD

**Issue by mkoenings** [OLIMEX/ESP32-ADF#7]
Hello, 
thanks for this great product. It works really well. However, I need the line-in input, in order to create an application for musical intruments. There is no pin available for this, correct ?  I am willing to sacrifice the microphones ( de-solder) if necessary. What else needs to be done ?  Which registers have to be changed ? Thanks a lot, Michael

**Comment by DanKoloff** [comment]
I think it is possible but I can't give you exact step-by-step details since we haven't done it ourselves and also there are multiple options. It would require some hardware changes for sure. Look at the schematic. You can either use the unused LIN2 or RIN2 or modify the already used LIN1 and RIN1. If you want to use the unused LIN2 or RIN2 are unrouted in our design (meaning you'd need to solder wires directly to ES8388's pins #22 and #21). Maybe if it was me I'd go that path and just solder two wires to the free pins and lead them to breadboard to experiment with them further. 

Alternatively if you want to use LIN1 for line input the first thing you would have to remove R27. 

ESP32-ADF uses Everest ES8388 so first make sure to take a look at ES8388 datasheet AND its user manual (the manual has some examples and register considerations).

**Comment by mkoenings** [comment]
thank you! I will try to use the LIN1,  I dont feel comfortable wiring these tinypins on the chip :-)
I wasnt aware of the user manual, that might be helpful.
Cheers!
